import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { UserProvider } from "@/context/UserProvider";
import { CatExistsProvider } from "@/context/CatExistProvider";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Cat Of The Day",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <UserProvider>
                    <CatExistsProvider>
                        <Header />
                        {children}
                        <Footer />
                    </CatExistsProvider>
                </UserProvider>
            </body>
        </html>
    );
}
